### PR TITLE
feature: inoreader & feedly support; options page; manifest v3 version

### PR DESCRIPTION
**Pull request by lcomplete**
I noticed that you become active in github, so i make this pr, i know this pr is a bad pull request, because it has too much breaking changes and some hacky code.

I just want to thank you for make a such good browser plugin, and i want help to build the plugin better, maybe you can use some code of mine.

I think auto refresh the toc when content change is a good feature for the payment version, and i simply add this feature in Inoreader and Feedly, there are few people like this too, maybe you can add this feature in newest version.

### CODE REVIEW

**Comment by FallenMax** [comment]
@lcomplete Thank you so much!

Smart TOC starts as a weekend hobby project, and I'm happy it become useful to other people :) 

To make it useful/delightful while still preserving simple/smart style, I have done a major overhaul to core mechanism, which fixed some issue this PR addresses (install 0.6.x and try):  

- Auto-refreshing is added, and works for general SPA sites, even for sites where article gets removed then re-added (Gitbook),  and works for dynamical contents with `content-visibility: auto` style.

- Panel positioning is (kinda) done right this time

- Feedly articles works as expected (the last time I checked). I have not tested on Inoreader, and I suppose it should also work, please let me know if there are still issues.

I have also made some additional features (dark theme, filter, toggle etc) and planning to release them as paid features. This is not to make a lot of money, it's only to motivate myself. The new code is not open sourced temporarily. I will figure out how to make a paid version AND open source :P

I'm grateful for your contribution to Smart TOC, would like to give pro license to you and other people who contributed to this project, when the Pro version is out. Thank you!

**Comment by FallenMax** [comment]
@lcomplete Btw, I noticed that you released forked extension here https://chrome.google.com/webstore/detail/smart-toc-%E6%99%BA%E8%83%BD%E7%BD%91%E9%A1%B5%E5%A4%A7%E7%BA%B2/ppdjhggfcaenclmimmdigbcglfoklgaf
If you don't mind, would you consider releasing it under another name (Smart Outline, Auto Outline, etc.)?  This is to avoid confusing for users. Thank you!

**Comment by lcomplete** [comment]
@FallenMax off course, i will do it today.

**Comment by lcomplete** [comment]
@FallenMax  Explain it, some people ask for publish my version to the chrome store, so i did that, i will change the extension's title, hope this don't bother you.

**Comment by FallenMax** [comment]
@lcomplete Thank you for understanding 😋

**Pull request closed without merging**
